frontend preparation
SterniXP/UIDPatienten pull request #1
Opened 2023-10-24 16:24 UTC by SterniXP

2023-10-24 17:42 UTC, slx666 requested changes
Deine getter/setter sind alle trivial. Hier würde ich mir Gedanken machen ob diese überhaupt benötigt werden. (So wie sie jetzt sind denke ich nicht)
Ansonsten ist das alles ganz gut bis auf ein paar Kleinigkeiten

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/ContactInfo.h
> +    QString getTelefonNumber() const;
`const QString&` als return type

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/ContactInfo.h
> +    QString getStreet() const;
Hier auch

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/ContactInfo.h
> +    QString getHouseNumber() const;
Hier auch

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/ContactInfo.h
> +    QString getPostalCode() const;
Hier auch

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/ContactInfo.h
> +    QString getCity() const;
Hier auch

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/Patient.h
> +    QString getTitle() const;
`const QString&` als return type

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/Patient.h
> +    QString getLastName() const;
Hier auch

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/Patient.h
> +    QString getFirstName() const;
Hier auch

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/Patient.h
> +    QDate getBirthDate() const;
Hier auch

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/contactinfo.cpp
> +ContactInfo::ContactInfo() {
ist die Existenz dieses Constructors wirklich nötig?

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/mainwindow.cpp
> +    PatientDialog *patientDialog;
`const auto patientDialog = new PatientDialog(this->ui);` ist mein Vorschlag

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/mainwindow.cpp
> +    patientDialog->setAttribute(Qt::WA_DeleteOnClose);//necessary to prevent memory leak (Qt doesnt clean up completely otherwise)
Wie gesagt, das parent ist für das löschen verantwortlich. Brauchst du also nicht unbedingt. Um einen memory leak zu verhindern, ist es wichtig, dass der Speicher **irgendwann** freigegeben wird. Wann genau ist prinzipiell egal. Wenn du den Speicherplatz direkt nach schließen des Dialoges freigeben möchtest, ist dieser approach defintiv in Ordnung.

2023-10-24 17:42 UTC, slx666 commented on UIDPatienten/mainwindow.cpp
> +        dialogMessage = "Wollen Sie " %  QString::number(amountSelected) % " Patienten loeschen?";
Wie kommts dass du "loeschen" schreibst? :D
QString ist ein UTF16 String

2023-10-24 22:02 UTC, SterniXP commented on UIDPatienten/mainwindow.cpp
> +    patientDialog->setAttribute(Qt::WA_DeleteOnClose);//necessary to prevent memory leak (Qt doesnt clean up completely otherwise)
ja muss leider so sein sonst leaked jedes geöffnete fenster 1-1,5mb

2023-10-25 08:56 UTC, SterniXP commented on UIDPatienten/contactinfo.cpp
> +ContactInfo::ContactInfo() {
ja verhindert nullpointer beim versuch auf diese werte zuzugreifen wenn diese noch nicht eingetragen wurden

2023-10-25 09:14 UTC, SterniXP commented on UIDPatienten/mainwindow.cpp
> +    QPushButton *confirmDeleteButton = messageBox.addButton(tr("Loeschen"), QMessageBox::YesRole);
ne weil sonst .settext und co nicht funktionieren

2023-10-25 09:21 UTC, merged